### ISSUE TITLE
Salinas 25X25 windowSize

### ISSUE THREAD

**Issue by sravyasr** [mahmad00/A-Fast-3D-CNN-for-HSIC#2]
Could you please share the modifications for salinas dataset withwindow size 25X25

**Comment by mahmad00** [comment]
Please change the size from 11 to 25 or whatever suits you the best according to your need and requirements.

**Comment by sravyasr** [comment]
Yes I did but colab is crashing for 25 window size. Could you please help me with that

**Comment by mahmad00** [comment]
It works fine at my end, Please check two things, 
1): Use of GPU and memory
2): Quality of your Internet connection.

Good luck!

**Comment by sravyasr** [comment]
Thank you for your response. It helps alot 
I encountered problem at createimagecubes function with windows size as 25. My memory is good and I'm using GPU with good internet. Still colab is crashing

**Comment by mahmad00** [comment]
I just re-executed the code and it works fine at my end with limited memory.

**Comment by sravyasr** [comment]
Thanks alot
