### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by gigi2299** [mahmad00/A-Fast-3D-CNN-for-HSIC#3]
hi,thanks for your amazing code,I run it in colab.Unfortunatly，there's something wrong with it,the accuracy of the classification result I test is only 25%.Could you help me find the reason? thanks again.

**Comment by mahmad00** [comment]
Thank you for your interest. Would you please like to let me know on which dataset you are trying and getting the reported accuracy? You can check the reported accuracies as the code has already been provided with the results. 

In any case, please check the number of training/validation/test samples. Patch size. The number of dimensions. Layers, etc.
